### ISSUE TITLE
Schema Checklist

### ISSUE THREAD

**Issue by iProgYou** [Flatout007/groovecamp#2]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [x] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
## Comments
- Get rid of presence true in the details column. Just use null: false (sinse these are DB constraints, not model validations)
- Password is not stored in the DB
- All of the foreign key should be indexed (it helps with associations)
- I am not sure what `user_albums_id` is. Shouldn't `artist_id`  be sufficient? If I remember from bandcamp, users and artists are basically the same thing no? We may want to talk that over
- I am not sure what `artist_albums_id` or `artist_songs_id` are. 
- Make sure to specify foreign keys like in the bluebird demo.

**Comment by iProgYou** [comment]
There are still a couple things that need to be figured out here. Comment in this thread when you have completed them.

**Comment by Flatout007** [comment]
- Got rid of presence true in the details column

**Comment by Flatout007** [comment]
- All of the foreign keys should be indexed

**Comment by Flatout007** [comment]
- Displays foreign keys in details column

**Comment by Flatout007** [comment]
QUESTION - Should my array of song_ids be a foreign key ?

**Comment by iProgYou** [comment]
- In the albums table, you don't want and array of `song_ids`. You will get the `song_ids` from the association.

**Comment by Flatout007** [comment]
- removed song_ids array

**Comment by iProgYou** [comment]
Lets talk about this a bit
