### ISSUE TITLE
Sample state

### ISSUE THREAD

**Issue by iProgYou** [Flatout007/groovecamp#4]
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
## Comments
- I think you will want a `song_ids` array within each individual album. Make sure it is only song ids
- I am not sure you need multiple artist ids in your album at first. I think it would be a good idea to only have one artist per album at first. If later you want to have multiple artist on one album I think that can be a feature you add later
- For songs, similar to albums, I think you only want one artist per song to start and also only one album id associated to a song. So no arrays there
- Your keys need to be `artistId` and `songId` as opposed to `artist_id` etc

**Comment by Flatout007** [comment]
- State's keys are camelCased
