### ISSUE TITLE
Frontend Routes

### ISSUE THREAD

**Issue by iProgYou** [Flatout007/groovecamp#5]
# Frontend Routes
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)
## Comments
- You will want an artists index that holds all the artist index items
- You will want a songs index here: `artist songs show`. It should also have song index items
- same thing as above but for albums

**Comment by Flatout007** [comment]
routes are displayed with inline coding text

**Comment by iProgYou** [comment]
- `/artist/:id` currently you have this displaying an `ArtistIndex`, but this looks like an artist show route (because of the id). What do you want to display on an artist show route?
- `/album/:id` same as above ^. This looks like an album show, but you are displaying an `AlbumIndex`. What would be displayed on an album show page?

**Comment by Flatout007** [comment]
- changed - ```AlbumIndex``` to - ```AlbumShowComponent```
- changed - ```ArtistIndex``` to - ```ArtistShowComponent```

**Comment by Flatout007** [comment]
- Since an artist can be a user I removed 
- ```/artist/:id``` 
         - ```ArtistShowComponent```
