### ISSUE TITLE
Backend Routes

### ISSUE THREAD

**Issue by iProgYou** [Flatout007/groovecamp#6]
# Backend Routes
- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show
## Comments
- You likely don't need a `GET /api/songs`. You can get the songs when you do `GET /api/albums/:id`

**Comment by Flatout007** [comment]
removed ```GET /api/songs``` from routes

**Comment by iProgYou** [comment]
- `GET /api/songs/:id` I am not sure if this route is necessary. What would a situation be where you would use it?

**Comment by Flatout007** [comment]
> * `GET /api/songs/:id` I am not sure if this route is necessary. What would a situation be where you would use it?

I Thought it might be useful when searching for a song.
